apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.11

patchesStrategicMerge:
  - argocd-server-service.yaml
  - argocd-repo-server-deploy.yaml
  - argocd-server-deploy.yaml
  - argocd-application-controller-statefulset.yaml


namespace: argocd