apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: argocd
type: Opaque
stringData:
  name: {{ .Release.Name }}
  server: https://{{ .Values.cluster_name }}.vcluster
  config: |
    {
      "bearerToken": "{{ .Values.argocd_token }}",
      "tlsClientConfig": {
        "insecure": true
      }
    }