apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project-clusters.yaml
  - vcluster-namespace.yaml
  - argocd-application.yaml
  - aws-controllers-ns.yaml
  - aws-ingress-controller-application.yaml
  - external-dns-application.yaml
  - ../base

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml